import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header/Header'
import Slider from '../components/Slider/Slider'
import NewsList from '../components/NewsList/NewsList'
import Footer from '../components/Footer/Footer'
import MainSlider1 from '../public/image/sliderSlide1.png'
import MainSlider2 from '../public/image/sliderSlide2.png'
import infoPicture from '../public/image/info-picture.png'
import TestImageNewsJPG from '../public/image/newsTestImage.png'
import huskyHug from '../public/image/husky-hug.png'

const news = [
  {
    id: '1',
    image: TestImageNewsJPG,
    title: 'Дорогие друзья! От всей души поздравляем вас с Новым годом!',
  },
  {
    id: '2',
    image: TestImageNewsJPG,
    title: 'Дорогие друзья! От всей души поздравляем вас с Новым годом! Дорогие друзья! От всей души поздравляем вас с Новым годом!',
  },
  {
    id: '3',
    image: TestImageNewsJPG,
    title: 'Дорогие друзья! От всей души поздравляем вас с Новым годом! Дорогие друзья! От всей души поздравляем вас с Новым годом! Дорогие друзья! От всей души поздравляем вас с Новым годом!',
  },
  {
    id: '4',
    image: TestImageNewsJPG,
    title: 'Дорогие друзья! От всей души поздравляем вас с Новым годом!',
  }
]


export default function Home() {
  const slides = [
    <Image key={1} src={MainSlider1} alt="Слайд 1" layout="responsive" />,
    <Image key={2} src={MainSlider2} alt="Слайд 2" layout="responsive" />,
  ]
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Slider slides={ slides } className='slider__main'/>
      <section className="information">
          <div className="wrapper">
            <div className='info'>
              <div className="info__middle">
                <h2>Как мы радуемся, когда в нашей жизни появляется что-то настоящее!</h2>
                <p className='info__ph'>
                  Особенно глубокие чувства, истинная дружба и любовь.
                  Наши питомцы – это те, кто безусловно и по-настоящему любит нас. Отношения с ними наполнены искренней радостью, добротой, гармонией.
                  <span className="info__ph--strong"> Чувства между нами и нашими питомцами – самые настоящие!</span>
                </p>
                <p className='info__ph'>
                  Ценим ли мы настоящие чувства? Правильно ли заботимся
                  о наших питомцах? Они полностью доверяют нам, и мы отвечаем за их здоровье, долголетие и жизнь.
                  <span className="info__ph--strong"> Настоящие чувства – это настоящая ответственность.</span>
                </p>
                <p className='info__ph'>
                  Здоровье наших любимцев во многом зависит от питания, ухода, образа жизни, нашего с ними взаимодействия.
                  <span className="info__ph--strong"> Лучшее выражение настоящих чувств к питомцам – забота и выбор качественных товаров для них.</span>
                </p>
              </div>
              <div className="info__image">
                <Image src={infoPicture} alt="Хозяева обнимают своих питомцев" width={445} height={476} />
              </div>
            </div>
          </div>
        </section>
        <section className='more'>
          <div className='more__image'>
            <Image src={huskyHug} alt="Хозяева обнимают своих питомцев" width={454} height={404} />
          </div>
          <div className='more__info'>
            <h2>Для тех, кто ценит и стремится к настоящему, мы создали бренд Еlato</h2>
            <button className='more__button gradient'>Подробнее о бренде</button>
          </div>
        </section>
        <section className='news'>
          <div className='wrapper'>
            <h2>Новости</h2>
            <NewsList className="news__list" news={ news } />
            <button className='news__button white'><p>Все новости</p></button>
          </div>
        </section>
        <Footer />
    </>
  )
}
